# from rust:1.69.0-alpine as builder
#
# workdir /usr/src/myapp
#
# run apk add --no-cache build-base nodejs npm openssl-dev pkgconfig glibc
# run npm install -g yarn
# run rustup target add wasm32-unknown-unknown
# run cargo install wasm-opt
# run cargo install --locked trunk
#
# copy . .
#
# run cargo build --release
#
# # # stage 2: run
# # from alpine:latest as runtime
# #
# # workdir /app
#
# # run apk add --no-cache libgcc
#
# # copy --from=builder /usr/local/cargo/bin /usr/local/cargo/bin
# # copy --from=builder /usr/src/myapp/target/release /app
#
# cmd ["make", "ssr_dev"]



# Use Debian-based Rust image
# FROM rust:1.69.0 as builder
#
# WORKDIR /usr/src/myapp
#
# RUN apt-get update && \
#     apt-get install -y build-essential nodejs npm openssl pkg-config && \
#     npm install -g yarn && \
#     rustup target add wasm32-unknown-unknown && \
#     cargo install wasm-opt && \
#     cargo install --locked trunk
#
# COPY . .
#
# RUN cargo build --release
#
# CMD ["make", "ssr_dev"]

FROM rust:1.69.0

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get update && apt-get install -y make nodejs g++ binaryen
RUN npm install -g yarn

WORKDIR /usr/src/ssr_server
COPY . .

# EXPOSE 8080

RUN rustup target add wasm32-unknown-unknown

# TODO: wasm-optは必要みたいだけど、やたらとサイズがでかいので削除したい気持ちが強い
# RUN cargo install wasm-opt
RUN cargo install --locked trunk

RUN cargo build --release
# COPY --from=node /usr/local/bin/yarn /usr/local/bin/

CMD ["make", "ssr_dev"]
