import json
import requests

html = '''
\n<p>Android開発をAndroid studioではなくvimで行いたくて、色々と詰まった箇所あるので記事にしてみました</p>\n\n\n\n<h2>手順</h2>\n\n\n\n<p><strong>Kotlinのinstall</strong></p>\n\n\n\n<p>まずはbrew経由でinstall</p>\n\n\n\n<pre class=\"wp-block-code\"><code lang=\"vim\" class=\"language-vim\">brew install kotlin\n\nkotlin --version\nKotlin version 1.6.10-release-923 (JRE 17.0.2+0)</code></pre>\n\n\n\n<p><strong>Syntax系</strong></p>\n\n\n\n<pre class=\"wp-block-code\"><code lang=\"vim\" class=\"language-vim\">[[plugins]]\nrepo = 'udalov/kotlin-vim'\non_ft = ['kotlin']\n\n# .vimrcにはこちらも追加。kotlinファイルをうまく認識してくれなかったので入れました\nautocmd BufReadPost *.kt setlocal filetype=kotlin</code></pre>\n\n\n\n<p><strong>lspの設定</strong></p>\n\n\n\n<p>まずはkotlin lspをclone</p>\n\n\n\n<p><a href=\"https://github.com/fwcd\" target=\"_blank\" rel=\"noreferrer noopener\">fwcd/kotlin-language-server</a></p>\n\n\n\n<pre class=\"wp-block-code\"><code lang=\"vim\" class=\"language-vim\">https://github.com/fwcd/kotlin-language-server.git\n\ncd ../<meta charset=\"utf-8\">kotlin-language-server\n./gradlew build</code></pre>\n\n\n\n<p>cloneが完了したら、coc-settingにこちらを追加</p>\n\n\n\n<pre class=\"wp-block-code\"><code lang=\"vim\" class=\"language-vim\">\"kotlin\": {\n    // LSPをdownloadしたpathを入れる\n    \"command\": \"/Users/masahirookubo/development/kotlin-language-server/server/build/install/server/bin/kotlin-language-server\",\n    \"filetypes\": [\"kotlin\"]\n}</code></pre>\n\n\n\n<figure class=\"wp-block-image size-large\"><img loading=\"lazy\" width=\"644\" height=\"480\" src=\"https://mokubo.website/wp-content/uploads/2022/03/Screen-Shot-2022-03-05-at-1.04.47-644x480.png\" alt=\"\" class=\"wp-image-4536\" srcset=\"https://mokubo.website/wp-content/uploads/2022/03/Screen-Shot-2022-03-05-at-1.04.47-644x480.png 644w, https://mokubo.website/wp-content/uploads/2022/03/Screen-Shot-2022-03-05-at-1.04.47-300x224.png 300w, https://mokubo.website/wp-content/uploads/2022/03/Screen-Shot-2022-03-05-at-1.04.47-768x573.png 768w, https://mokubo.website/wp-content/uploads/2022/03/Screen-Shot-2022-03-05-at-1.04.47.png 822w\" sizes=\"(max-width: 644px) 100vw, 644px\" /></figure>\n\n\n\n<p>若干動作が遅い気もしますが、上記の対応でneovimでAndroid開発をサクサク(一応)行えるようになりました！</p>\n\n\n\n<h2>参考記事</h2>\n\n\n\n<p><a href=\"https://github.com/fwcd/kotlin-language-server/blob/main/BUILDING.md\" target=\"_blank\" rel=\"noreferrer noopener\" title=\"https://github.com/fwcd/kotlin-language-server/blob/main/BUILDING.md\">Building</a></p>\n\n\n\n<p><a href=\"https://github.com/fwcd/kotlin-language-server/blob/main/EDITORS.md\" target=\"_blank\" rel=\"noreferrer noopener\">Editor Integration</a></p>\n
'''

data = json.dumps(html)
headers = {'Content-Type': 'application/json'}

response = requests.post('https://html-sanitization-server-3s6gqspbuq-an.a.run.app/api/sanitization_of_html', headers=headers, data=data)

print(response.json())
