FROM rust:1.69.0

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get update && apt-get install -y make nodejs g++ binaryen
RUN npm install -g yarn

WORKDIR /usr/src/ssr_server
COPY . .

RUN rustup target add wasm32-unknown-unknown

# TODO: wasm-optは必要みたいだけど、やたらとサイズがでかいので削除したい気持ちが強い
# RUN cargo install wasm-opt
RUN cargo install --locked trunk

RUN cargo build --release
# COPY --from=node /usr/local/bin/yarn /usr/local/bin/

EXPOSE 8080

# CMD ["make", "ssr_dev"]
